const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
$('#year').textContent=new Date().getFullYear();
const saved=localStorage.getItem('portfolio-theme'); if(saved==='light') document.body.classList.add('light');
const themeToggle=$('#themeToggle');
function syncTheme(){const light=document.body.classList.contains('light');themeToggle.setAttribute('aria-pressed',String(light));themeToggle.textContent=light?'☾':'☼';themeToggle.setAttribute('aria-label',light?'Switch to dark theme':'Switch to light theme')}
syncTheme(); themeToggle.addEventListener('click',()=>{document.body.classList.toggle('light');localStorage.setItem('portfolio-theme',document.body.classList.contains('light')?'light':'dark');syncTheme()});
const menuBtn=$('#menuBtn'), navLinks=$('#navLinks');
menuBtn.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open));menuBtn.setAttribute('aria-label',open?'Close navigation':'Open navigation')});
$$('.nav-links a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menuBtn.setAttribute('aria-expanded','false')}));
function updateProgress(){const h=document.documentElement, max=h.scrollHeight-h.clientHeight;$('#progress').style.width=max>0?`${(h.scrollTop/max)*100}%`:'0%'}
window.addEventListener('scroll',updateProgress,{passive:true}); updateProgress();
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12}); $$('.reveal').forEach(el=>io.observe(el));
const featured=['finsecure-core','production-rag-system','Data-Leakage-Detection-System','mlops_orchestrator','healthcare-fraud-hub','graph-pulse','ecommerce-retention','Better-Fullstack','agentic-system'];
const descriptions={'finsecure-core':'Security-focused engineering for reliable financial workflows and risk-aware systems.','production-rag-system':'Production-oriented retrieval-augmented generation architecture for grounded AI applications.','Data-Leakage-Detection-System':'Machine-learning workflow focused on identifying and preventing data leakage.','mlops_orchestrator':'Automation and orchestration patterns for repeatable machine-learning operations.','healthcare-fraud-hub':'Analytics and ML concepts for identifying suspicious patterns in healthcare data.','graph-pulse':'Graph-based experimentation for analyzing connected data and relationships.','ecommerce-retention':'Data-driven analysis of customer retention and e-commerce behavior.','Better-Fullstack':'Full-stack experiments focused on better production web applications.','agentic-system':'Exploration of agentic architectures and AI-powered workflows.'};
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function loadGitHub(){const grid=$('#projectGrid');try{const r=await fetch('https://api.github.com/users/Sukumar-Elley/repos?per_page=100&sort=updated',{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw Error('GitHub unavailable');const repos=await r.json();$('#repoCount').textContent=repos.length;const chosen=featured.map(name=>repos.find(x=>x.name===name)).filter(Boolean).slice(0,6);if(!chosen.length)throw Error('No featured repositories');grid.innerHTML=chosen.map((p,i)=>`<article class="project reveal visible"><span class="number">${String(i+1).padStart(2,'0')} / PROJECT</span><h3>${escapeHtml(p.name.replaceAll('-',' '))}</h3><p>${escapeHtml(descriptions[p.name]||p.description||'A software project from my GitHub portfolio.')}</p><div class="project-foot"><div class="tags"><span class="tag">${escapeHtml(p.language||'Code')}</span><span class="tag">${p.stargazers_count} ★</span></div><a href="${escapeHtml(p.html_url)}" target="_blank" rel="noopener noreferrer" aria-label="Open ${escapeHtml(p.name)} repository">View project ↗</a></div></article>`).join('');}catch(e){grid.innerHTML='<div class="loading">GitHub projects are temporarily unavailable. <a class="text-link" href="https://github.com/Sukumar-Elley?tab=repositories" target="_blank" rel="noopener noreferrer">Browse repositories ↗</a></div>';}}
async function loadProfile(){try{const r=await fetch('https://api.github.com/users/Sukumar-Elley',{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw Error();const p=await r.json();$('#followerCount').textContent=p.followers??'—';}catch{}}
loadGitHub(); loadProfile();